### ISSUE TITLE
ZX_RRNG address correct?

### ISSUE THREAD

**Issue by akohlsmith** [sparkfun/ZX_Distance_and_Gesture_Sensor#4]
I'm the author of the ZX software (the software in the sensor itself). Are you sure that you have the ZX_RRNG address correct? REGVER 0x01 MODEL 0x01 should not report anything at register 0x0e (i.e. reading register 0x0e will always return zero).

If you could verify this behaviour this on your production sensors I'll fork the code and send a pull request.

**Comment by ShawnHymel** [comment]
Hi Andrew, sorry it's taken me so long to get to this bug. I spit out the contents of LRNG and RRNG from our production ZX Sensor, and they both read "0." According to the [I2C Register Map](https://cdn.sparkfun.com/datasheets/Sensors/Proximity/XYZ%20I2C%20Registers%20v1.zip) that XYZ sent me, LRNG and RRNG are implemented. I just don't see them doing any thing right now. I don't mind leaving the definitions in, because they aren't used in the code.

**Comment by bboyho** [comment]
Unfortunately, the ZX distance and gesture sensor [SKU-12780](https://www.sparkfun.com/products/retired/12780) has been retired. This looks like the issue has been addressed and will be left as is.  I will be closing this issue and archiving the GitHub repository.

There is another version available with the surface mount ICs [ ZX Distance and Gesture Sensor SMD [SEN-13162](https://www.sparkfun.com/products/13162) ] so the associated Arduino Library will be kept open [SparkFun_ZX_distance_and_Gesture_Sensor_Arduino_Library](https://github.com/sparkfun/SparkFun_ZX_Distance_and_Gesture_Sensor_Arduino_Library).
